import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import CreateUser from '../components/CreateUser'
import User from '../components/User'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <User />
        <CreateUser/>
      </main>

  
    </div>
  )
}

export default Home
